name: fetch_data_examples
description:
  An example about fetching data over the internet using the http package.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: '^0.13.5'
